### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by urban-1** [newinnovations/remote-edit-ni#1]
Hi there,

I also have a fork of this project and I am using it on a daily basis. I have added a few features that do not exist in other forks. I have also attempted to consolidate forks few months back but without success... So I was wondering if you are interested in merging our forks (I can make a PR if you like what you see)

Also, I have shamelessly copied your atom 1.23.x fix and tidied it up a bit (early returns to avoid extra indentation). You can find this at:

https://github.com/urban-1/remote-edit2/commit/8fead32d48893f749b37082e109cb3430d70f51f

Many thanks for this fix, it saved me!

Let me know if you are interested in merging (I do not have my own atom package, instead I install from URL...)

**Comment by newinnovations** [comment]
Hi Urban-1,

Thanks for reaching out. I think we are in the same boat. I'm also using remote-edit on a daily basis and started a fork to add some features for my personal taste. Later it was just fixes for incompatibilities with newer releases of atom.

Good job cleaning up remote-edit-editor.js. I just checked it in.

Merging our forks is probably a good idea. We'll need some testing to see if both our needs can be met, but if so let's do it.

If you could create a PR, we could start by making branch to do some testing.

**Comment by jltajada** [comment]
remote edit its a simply shit.

**Comment by urban-1** [comment]
@jltajada , well, we are trying to fix this... have you tried our `devel` branch?

Not tested installation:
```
git clone https://github.com/newinnovations/remote-edit-ni.git
cd remote-edit-ni
git checkout devel
apm install
apm link
```

**Comment by newinnovations** [comment]
@jltajada not sure whether you refer to the original project or this fork. This fork works for me and a lot of other people. If you found an issue with this fork do create a new issue. But in any case please try to be a nice bloke.

**Comment by newinnovations** [comment]
Just merged the development branch into master

**Comment by urban-1** [comment]
Brought my fork up to your master, installed and testing but so far so good :) - Feel free to close this whenever you want.

**Comment by newinnovations** [comment]
Doing it now ;-)
