### ISSUE TITLE
No shortcuts work

### ISSUE THREAD

**Issue by janstieler** [newinnovations/remote-edit-ni#10]
Hi,
I'm on OSX 10.11 with Atom 1.25.0. I can't use any shortcuts on my system for the remote edit.
On the package from sveale all shortcuts worked with cmd+alt+… or cmd+ctrl+…
Why have you changed this shortcuts?

Cheers

**Comment by urban-1** [comment]
Hi @janstieler 

You are right! I forgot to update the README file :( - doing it now

I am using Mac at work and Linux at home and the shortcuts between the two of them were different which was very confusing. @newinnovations  has changed the Win/Linux ones to all be under <kbd>Alt+r ...</kbd> which makes sense. In the last release, I made the Mac shortcuts the same using <kbd>Cmd+r ...</kbd>. This, more or less, requires the same hand movement on the keyboard allowing seamless work between Linux and Mac. 

You can always remap with `keymap.json` but I would suggest you keep the defaults. Once you get used to them they make a lot more sense and are easy to remember:

- <kbd>Cmd+r b</kbd> -
Select remote host and start browsing in / or last directory (when selected in preferences).

- <kbd>Cmd+r m</kbd> -
Browse remote host in directory of the current editor tab.

-   <kbd>Cmd+r v</kbd> -
Show/hide remote-edit panel

- <kbd>Cmd+r o</kbd> -
Show open (downloaded) remote files.

- <kbd>Cmd+r f</kbd> -
Give focus to the remote-edit file browser. This allows you to navigate with
keyboard (up/down/enter/backspace)

Give them a try and let me know what you think!

NOTE: <kbd>Cmd+r</kbd> need to be pressed together, you can then release them and hit they key that you want (for example `b` to browse hosts)

**Comment by janstieler** [comment]
Okay I can follow your mentions. But I have to use my own because I got conflicts with other shortcuts eg. from Atom Beautify.
