### ISSUE TITLE
Problem if an deleted folder is open

### ISSUE THREAD

**Issue by janstieler** [newinnovations/remote-edit-ni#12]
Hi,
today I have a special situation which is a little bit stupid.
If I have an folder open which is deleted in the meanwhile I can't go up in the folderhirachy to an existing folder. What also not is a solution is to open the connection angain because it will open the last opened folder. I have first to connect to another host and than again to first host.

Cheers

**Comment by urban-1** [comment]
I have not tried this as yet but can you use the filter to change folder?

For example:
![screen shot 2018-04-10 at 17 40 37](https://user-images.githubusercontent.com/796204/38570756-79f362b4-3ce6-11e8-94d6-56a6b39302b3.png)

and hitting <kbd>Enter</kbd> should take you to that folder, regardless of if the current directory has been deleted

**Comment by newinnovations** [comment]
May be we better address this as part of #17
