### ISSUE TITLE
Add ability to create remote folder

### ISSUE THREAD

**Issue by Nogginboink** [newinnovations/remote-edit-ni#18]
This is an enhancement request rather than a bug, but the ability to create a folder on the remote machine sure would be handy.

**Comment by Nogginboink** [comment]
Clearly, I am an idiot. This ability already exists in the context menu..

**Comment by urban-1** [comment]
Hi @Nogginboink :) 

You can also create a folder via a command (<kbd>Ctrl+Shift+P</kbd>) and then type "Create Folder" (or file). This will create the new item in the current location of the remote-edit file browser.

Feel free to close this if you have no more questions :)
