### ISSUE TITLE
Same host different user problem

### ISSUE THREAD

**Issue by janstieler** [newinnovations/remote-edit-ni#20]
Hi,
today i had a new problem. I have two connections to the same host but with different users and folders. But it will load everytime the same connection equal with I select.
I think it is selcting the first one in the remoteEdit.json but i'm not really sure.

Cheers

**Comment by urban-1** [comment]
Hi @janstieler 

This should be a fast fix - made a PR

Thanks for reporting!

**Comment by janstieler** [comment]
Thanks for fixing it so fast.
