### ISSUE TITLE
Failed to load the remote-edit-ni package

### ISSUE THREAD

**Issue by vinlyx** [newinnovations/remote-edit-ni#25]
[Enter steps to reproduce:]

1. Upgrade remote-edit-ni to latest version.
2. restart atom

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Unknown Windows version
**Thrown From**: [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) package 3.4.0

### Stack Trace

Failed to load the remote-edit-ni package

```
At variable @input-background-color-focus is undefined in C:\Users\VincentLi\.atom\packages\remote-edit-ni\styles\remote-edit.less:316:23

LessError: variable @input-background-color-focus is undefined
at C:\Users\VincentLi\.atom\packages\remote-edit-ni\styles\remote-edit.less:316:23

Line number: 316
variable @input-background-color-focus is undefined
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
file-icons 2.1.21 
highlight-selected 0.13.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
remote-edit-ni 3.4.0 
sync-settings 0.8.6 
todo-show 2.3.0 
```

**Comment by urban-1** [comment]
Hi @vinlyx, this is a UI/style issue. The variable `@input-background-color-focus` is defined in `atom-one` theme but not in the `atom-material` that you use. In fairness this is only defined in ["ui-variables-custom.less"](https://github.com/atom/one-light-ui/blob/master/styles/ui-variables-custom.less) and not in the [standard ones](https://github.com/atom/atom/blob/master/static/variables/ui-variables.less).

I will have to replace it with something but not sure yet - will take some time. The fastest way around is to edit `C:\Users\VincentLi\.atom\packages\remote-edit-ni\styles\remote-edit.less` line 316 and replace that variable with a color of your choosing, for example:

```
atom-text-editor.editor.is-focused .password-lines .line span.syntax--text:before {
    background-color:  white !important;
}
```
 The relevant part in the `one` theme is:

```
@ui-syntax-color: @syntax-background-color;

// Color guards -----------------
@ui-s-h: hue(@ui-syntax-color);
.ui-hue() when (@ui-s-h = 0) { @ui-hue: 220; } // Use blue hue when no saturation
.ui-hue() when (@ui-s-h > 0) { @ui-hue: @ui-s-h; }
.ui-hue();
...
@input-background-color-focus:      hsl(@ui-hue, 100%, 96%);
```

Let me know if this solves you problem for now. I need more time to come up with a better solution :)
