### ISSUE TITLE
remote-edit-ni not updating

### ISSUE THREAD

**Issue by dmase44** [newinnovations/remote-edit-ni#28]
This package update draws errors and will not update remote-edit-ni version 3.42 to 3.5.0 on Atom 1.28.1 running Win 10  and my other machine with Atom 1.29.0 running Win 10.  I have node v8.11.3 and npm v5.6.0 on both computers.

> keytar@3.0.2 install C:\Users\Dave\AppData\Local\Temp\apm-install-dir-118715-728-648472.0808i4fgvi\node_modules\remote-edit-ni\node_modules\keytar
> node-gyp rebuild

C:\Users\Dave\AppData\Local\Temp\apm-install-dir-118715-728-648472.0808i4fgvi\node_modules\remote-edit-ni\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> platform-folders@0.2.7 install C:\Users\Dave\AppData\Local\Temp\apm-install-dir-118715-728-648472.0808i4fgvi\node_modules\remote-edit-ni\node_modules\platform-folders
> node-gyp rebuild

C:\Users\Dave\AppData\Local\Temp\apm-install-dir-118715-728-648472.0808i4fgvi\node_modules\remote-edit-ni\node_modules\platform-folders>if not defined npm_config_node_gyp (node "C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\Dave\AppData\Local\Temp\apm-install-dir-118715-728-648472.0808i4fgvi
`-- (empty)

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\Dave\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Dave\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dave\AppData\Local\Temp\apm-install-dir-118715-728-648472.0808i4fgvi\node_modules\remote-edit-ni\node_modules\keytar
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\Dave\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\Dave\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Dave\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dave\AppData\Local\Temp\apm-install-dir-118715-728-648472.0808i4fgvi\node_modules\remote-edit-ni\node_modules\platform-folders
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Dave\AppData\Local\Temp\apm-install-dir-118715-728-648472.0808i4fgvi\package.json'
npm WARN apm-install-dir-118715-728-648472.0808i4fgvi No description
npm WARN apm-install-dir-118715-728-648472.0808i4fgvi No repository field.
npm WARN apm-install-dir-118715-728-648472.0808i4fgvi No README data
npm WARN apm-install-dir-118715-728-648472.0808i4fgvi No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@3.0.2 (node_modules\remote-edit-ni\node_modules\keytar):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@3.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\Dave\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Dave\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Dave\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Dave\\.atom\\.apmrc" "install" "C:\\Users\\Dave\\AppData\\Local\\Temp\\d-118715-728-19alh83.ns89z4cxr\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! platform-folders@0.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the platform-folders@0.2.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the platform-folders package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs platform-folders
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls platform-folders
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Dave\AppData\Local\Temp\apm-install-dir-118715-728-648472.0808i4fgvi\npm-debug.log
npm ERR! code 1

**Comment by newinnovations** [comment]
We have found better way to find a safe location for storing the remote files locally. However a required package for this seems not to install on Windows without python being installed. It is now an optional package.

**Comment by dmase44** [comment]
Thanks for your quick response. I installed python and all is well.
