### ISSUE TITLE
Can't add new ftp/sftp server

### ISSUE THREAD

**Issue by janstieler** [newinnovations/remote-edit-ni#3]
Hi,
I have problems to add a new ftp/sftp server to remote-edit-ni.
If I open the menu or the shortcut (shift+f) nothing happend.
The only way is actually to add it manually to the json file.

Cheers

**Comment by urban-1** [comment]
Hello @janstieler, can you provide some more information:

- atom version
- plugin version

I cannot reproduce on atom 1.23.3. My way of adding hosts is: `Alt+r+B` (opens "Browse Hosts") and in that view `Shift+s/f` (Opens new s/ftp host)

**Comment by cabal95** [comment]
Running 1.25.0 does nothing when I click to add a new SFTP or FTP host. Nothing shows up in console either. The other 3 menu items seem to work fine (though there isn't a ton I can test without a host).

**Comment by urban-1** [comment]
Confirmed - same behavior on 1.23.3 and 1.25.0: Shortcuts work, menus don't. I will have to check this tomorrow at some point see why it is happening.

**Comment by cabal95** [comment]
@urban-1 Can you give me more specific instructions on how to use the shortcuts? I'm not sure what `Alt+r+B` means.  I tried Alt-r following by Alt-B but that didn't do it.

**Comment by urban-1** [comment]
@cabal95 The keyboard shortcuts for accessing the same functionality are all based on `Alt+r` (with both keys down), release both and then press `b`. A dialog will appear which should list all of the configured hosts (none in your case I assume). While in that view `Shift+s` (both keys down again) should open another dialog which allows you to configure a new sftp host. 

Hope it helps!

**Comment by newinnovations** [comment]
Key bindings worked, but menu bindings still contained the old naming and did not work. Fix by @urban-1 applied and released on atom.io.
