### ISSUE TITLE
Uncaught TypeError: Cannot read property 'deletePassword' of undefined

### ISSUE THREAD

**Issue by scouttle** [newinnovations/remote-edit-ni#33]
I was attempting to create a new SFTP host. 

I selected "Private key" under authentication settings, but **did not enter the passphrase associated with the private key**. 

The attempt to add the host failed. I repeated these same steps and was able to reproduce. 

The only change I had made to the default settings was to set "Store passwords using node-keytar" to be true (default value is false). 

Changing "Store passwords using node-keytar" back to false allowed me to add a new SFTP host with the same settings (auth via key, no passphrase entered). 

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) package 3.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'deletePassword' of undefined

```
At /Users/scout/.atom/packages/remote-edit-ni/lib/view/host-view.coffee:174

TypeError: Cannot read property 'deletePassword' of undefined
    at HostView.module.exports.HostView.confirm (/packages/remote-edit-ni/lib/view/host-view.coffee:174:20)
    at /packages/remote-edit-ni/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/remote-edit-ni/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/remote-edit-ni/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:56.3.0 command-palette:toggle (div.package-detail.panels-item)
     -1:50 core:confirm (input.hidden-input)
     -1:50 remote-edit:browse (div.package-detail.panels-item)
     -1:29.2.0 core:backspace (input.hidden-input)
     -1:28.3.0 core:confirm (input.hidden-input)
     -1:26.8.0 command-palette:toggle (div.package-detail.panels-item)
  3x -1:21.2.0 core:move-down (input.hidden-input)
     -1:20 core:confirm (input.hidden-input)
     -1:20 remote-edit:new-sftp-host (div.package-detail.panels-item)
  3x -1:03.9.0 host-view:focus-next (input.hidden-input)
```

### Non-Core Packages

```
remote-edit-ni 3.5.1 
```

**Comment by newinnovations** [comment]
Not using node-keytar myself, it is a feature from the original package. May look into it in the future (little time now). Patches welcome of course.
