### ISSUE TITLE
Lost host list?

### ISSUE THREAD

**Issue by IanCabell** [newinnovations/remote-edit-ni#36]
Opened Atom today, went to remote-edit to connect to a host, and it says there aren't any in there?

Where would I look for the hosts file to see if something is corrupted or something?

**Comment by newinnovations** [comment]
It happened to me once or twice. It sucks. We are not really sure what causes this. @urban-1 suggested he thought it may be caused by using the atom devtools.

The hosts are stored in remoteEdit.json in atom config directory (~/.atom/remoteEdit.json on linux).

**Comment by IanCabell** [comment]
@urban-1 may be right? I opened devtools to change the color of the highlighted host name, and that may have caused the issue. Thanks for letting me know where the file is, so at least I can keep a copy :)

**Comment by urban-1** [comment]
Hi @IanCabell - I never found out what exactly happens, but it seemed to happen when the devtools reload the view (Cmd+R does that if the focus is on the console).

As a workaround I use https://atom.io/packages/sync-settings and add this file to the list to backup so I always have a copy
