### ISSUE TITLE
Stuck on Connecting...

### ISSUE THREAD

**Issue by JamesKBowler** [newinnovations/remote-edit-ni#37]
Ubuntu 16.04
Atom 1.26.1 x64

![image](https://user-images.githubusercontent.com/24221328/45941783-a1e7d880-bfd7-11e8-85a8-dbebf8c8ef3c.png)

![image](https://user-images.githubusercontent.com/24221328/45941668-36057000-bfd7-11e8-9176-d0fc2ea304ec.png)

![image](https://user-images.githubusercontent.com/24221328/45941628-0bb3b280-bfd7-11e8-8051-5f83b7c664e7.png)

**Comment by urban-1** [comment]
Hi @JamesKBowler - do you see any errors or exceptions on the console. I have only seen this when there is a network problem but this is not the case here...

**Comment by JamesKBowler** [comment]
Hi @urban-1 , thank you for your response.

![image](https://user-images.githubusercontent.com/24221328/45942204-6fd77600-bfd9-11e8-8059-05d4b76d5d4c.png)

**Comment by JamesKBowler** [comment]
hmm..

It is now working, the fix was to restart the application. If in doubt turn it off and on : )


Thank you

Closing issue..
