### ISSUE TITLE
Hidden (dot) files don't show on file list

### ISSUE THREAD

**Issue by surak** [newinnovations/remote-edit-ni#43]
It seems impossible to open files when the name begins with a dot.

**Comment by urban-1** [comment]
There should be an option to enable hidden files in the settings of the package:

![image](https://user-images.githubusercontent.com/796204/68119101-6de52380-ff0a-11e9-85eb-1d6a7b872a91.png)

What I see in my browser is:

![image](https://user-images.githubusercontent.com/796204/68119118-85241100-ff0a-11e9-9f41-917d137d4a51.png)

@newinnovations I think this one should close and maybe reopened later with more info if required
